/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as AppRouteImport } from './../routes/_app'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as AppProductsRouteImport } from './../routes/_app/products'
import { Route as AppHomeRouteImport } from './../routes/_app/home'
import { Route as AppBrandsRouteRouteImport } from './../routes/_app/brands/route'
import { Route as AppCategoriesIndexRouteImport } from './../routes/_app/categories/index'
import { Route as AppBrandsAddRouteImport } from './../routes/_app/brands/add'
import { Route as AppBrandsEditBrandIdRouteImport } from './../routes/_app/brands/edit.$brandId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandsRouteRoute = AppBrandsRouteRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesIndexRoute = AppCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandsAddRoute = AppBrandsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppBrandsRouteRoute,
} as any)
const AppBrandsEditBrandIdRoute = AppBrandsEditBrandIdRouteImport.update({
  id: '/edit/$brandId',
  path: '/edit/$brandId',
  getParentRoute: () => AppBrandsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brands': typeof AppBrandsRouteRouteWithChildren
  '/home': typeof AppHomeRoute
  '/products': typeof AppProductsRoute
  '/brands/add': typeof AppBrandsAddRoute
  '/categories/': typeof AppCategoriesIndexRoute
  '/brands/edit/$brandId': typeof AppBrandsEditBrandIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brands': typeof AppBrandsRouteRouteWithChildren
  '/home': typeof AppHomeRoute
  '/products': typeof AppProductsRoute
  '/brands/add': typeof AppBrandsAddRoute
  '/categories': typeof AppCategoriesIndexRoute
  '/brands/edit/$brandId': typeof AppBrandsEditBrandIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/brands': typeof AppBrandsRouteRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/brands/add': typeof AppBrandsAddRoute
  '/_app/categories/': typeof AppCategoriesIndexRoute
  '/_app/brands/edit/$brandId': typeof AppBrandsEditBrandIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brands'
    | '/home'
    | '/products'
    | '/brands/add'
    | '/categories/'
    | '/brands/edit/$brandId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brands'
    | '/home'
    | '/products'
    | '/brands/add'
    | '/categories'
    | '/brands/edit/$brandId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/brands'
    | '/_app/home'
    | '/_app/products'
    | '/_app/brands/add'
    | '/_app/categories/'
    | '/_app/brands/edit/$brandId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands': {
      id: '/_app/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof AppBrandsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories/': {
      id: '/_app/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AppCategoriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands/add': {
      id: '/_app/brands/add'
      path: '/add'
      fullPath: '/brands/add'
      preLoaderRoute: typeof AppBrandsAddRouteImport
      parentRoute: typeof AppBrandsRouteRoute
    }
    '/_app/brands/edit/$brandId': {
      id: '/_app/brands/edit/$brandId'
      path: '/edit/$brandId'
      fullPath: '/brands/edit/$brandId'
      preLoaderRoute: typeof AppBrandsEditBrandIdRouteImport
      parentRoute: typeof AppBrandsRouteRoute
    }
  }
}

interface AppBrandsRouteRouteChildren {
  AppBrandsAddRoute: typeof AppBrandsAddRoute
  AppBrandsEditBrandIdRoute: typeof AppBrandsEditBrandIdRoute
}

const AppBrandsRouteRouteChildren: AppBrandsRouteRouteChildren = {
  AppBrandsAddRoute: AppBrandsAddRoute,
  AppBrandsEditBrandIdRoute: AppBrandsEditBrandIdRoute,
}

const AppBrandsRouteRouteWithChildren = AppBrandsRouteRoute._addFileChildren(
  AppBrandsRouteRouteChildren,
)

interface AppRouteChildren {
  AppBrandsRouteRoute: typeof AppBrandsRouteRouteWithChildren
  AppHomeRoute: typeof AppHomeRoute
  AppProductsRoute: typeof AppProductsRoute
  AppCategoriesIndexRoute: typeof AppCategoriesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBrandsRouteRoute: AppBrandsRouteRouteWithChildren,
  AppHomeRoute: AppHomeRoute,
  AppProductsRoute: AppProductsRoute,
  AppCategoriesIndexRoute: AppCategoriesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
