/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as LayoutRouteImport } from './../routes/_layout'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as LayoutProductsRouteImport } from './../routes/_layout/products'
import { Route as LayoutHomeRouteImport } from './../routes/_layout/home'
import { Route as LayoutCategoriesRouteImport } from './../routes/_layout/categories'
import { Route as LayoutBrandsRouteImport } from './../routes/_layout/brands'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutProductsRoute = LayoutProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHomeRoute = LayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCategoriesRoute = LayoutCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBrandsRoute = LayoutBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brands': typeof LayoutBrandsRoute
  '/categories': typeof LayoutCategoriesRoute
  '/home': typeof LayoutHomeRoute
  '/products': typeof LayoutProductsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brands': typeof LayoutBrandsRoute
  '/categories': typeof LayoutCategoriesRoute
  '/home': typeof LayoutHomeRoute
  '/products': typeof LayoutProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/brands': typeof LayoutBrandsRoute
  '/_layout/categories': typeof LayoutCategoriesRoute
  '/_layout/home': typeof LayoutHomeRoute
  '/_layout/products': typeof LayoutProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/brands' | '/categories' | '/home' | '/products'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/brands' | '/categories' | '/home' | '/products'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/brands'
    | '/_layout/categories'
    | '/_layout/home'
    | '/_layout/products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/products': {
      id: '/_layout/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof LayoutProductsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/home': {
      id: '/_layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutHomeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/categories': {
      id: '/_layout/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof LayoutCategoriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/brands': {
      id: '/_layout/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof LayoutBrandsRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutBrandsRoute: typeof LayoutBrandsRoute
  LayoutCategoriesRoute: typeof LayoutCategoriesRoute
  LayoutHomeRoute: typeof LayoutHomeRoute
  LayoutProductsRoute: typeof LayoutProductsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBrandsRoute: LayoutBrandsRoute,
  LayoutCategoriesRoute: LayoutCategoriesRoute,
  LayoutHomeRoute: LayoutHomeRoute,
  LayoutProductsRoute: LayoutProductsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
